sudo: required
services:
  - docker

# before_install:
#   - docker build -t prakhartewari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prakhartewari/react-test npm test

after_success:
  - docker build -t prakhartewari/multi-client ./client
  - docker build -t prakhartewari/multi-nginx ./nginx
  - docker build -t prakhartewari/multi-server ./server
  - docker build -t prakhartewari/multi-worker ./worker

  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push prakhartewari/multi-client
  - docker push prakhartewari/multi-nginx
  - docker push prakhartewari/multi-server
  - docker push prakhartewari/multi-worker